apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-config
  namespace: custom-metrics
  labels:
    app: prometheus-adapter
data:
  config.yaml: |
    rules:
      - seriesQuery: 'nv_inference_request_success{namespace!="",pod!=""}'
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: "nv_inference_request_success"
          as: "nv_inference_requests_per_second"
        metricsQuery: 'sum(rate(nv_inference_request_success{<<.LabelMatchers>>}[1m])) by (<<.GroupBy>>)'
      - seriesQuery: 'nv_inference_request_duration_us{namespace!="",pod!=""}'
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: "^(.*)_us"
          as: "${1}_milliseconds"
        metricsQuery: 'rate(nv_inference_request_duration_us[1m]) / 1000'
      - seriesQuery: 'nv_gpu_utilization{namespace!="",pod!=""}'
        resources:
          overrides:
            namespace:
              resource: namespace
            pod:
              resource: pod
        name:
          matches: "^(.*)_utilization"
          as: "${1}_utilization"
        metricsQuery: 'avg(nv_gpu_utilization) by (namespace, pod)'
