apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-metrics-prometheus-adapter
  namespace: custom-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-adapter
  template:
    metadata:
      name: prometheus-adapter
      labels:
        app: prometheus-adapter
    spec:
      serviceAccountName: custom-metrics-prometheus-adapter
      containers:
      - name: prometheus-adapter
        # image: registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.11.2
        image: directxman12/k8s-prometheus-adapter-amd64:v0.8.2
        imagePullPolicy: IfNotPresent
        args:
        - /adapter
        - --cert-dir=/tmp/cert
        - --logtostderr=true
        - '--prometheus-url=http://kube-prometheus-stack-prometheus.monitoring.svc:9090'
        - '--metrics-relist-interval=1m'
        - '--v=4'
        - '--config=/etc/adapter/config.yaml'
        - --secure-port=6443 # Enaable secure port
        ports:
        - name: https
          containerPort: 6443
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: https
            scheme: HTTPS
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["all"]
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 10001
        volumeMounts:
        - name: config
          mountPath: /etc/adapter/
          readOnly: true
        - mountPath: /tmp
          name: tmp
      volumes:
      - name: config
        configMap:
          name: custom-metrics-config
      - name: tmp
        emptyDir: {}
