apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-prometheus-adapter
  namespace: custom-metrics
  labels:
    app: prometheus-adapter
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 6443
    name: https
  selector:
    app: prometheus-adapter
  type: ClusterIP
